import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { getLocale, getMessages } from "next-intl/server";

import Providers from "@/common/context/providers";
import { AppSidebar } from "@/common/components/navigation/AppSidebar";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Go&Gospel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${nunito.className} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <Providers>
            <AppSidebar />
            <main className="w-full relative">{children}</main>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
