import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import Providers from "@/common/context/providers";
import { AppHeader } from "@/common/components/navigation/AppHeader";
import "./globals.css";

const nunito = Nunito({ subsets: ["latin"], variable: "--font-nunito" });

export const metadata: Metadata = {
  title: "Go&Gospel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${nunito.variable} font-sans antialiased bg-gray-100 `}>
        <NextIntlClientProvider messages={messages}>
          <Providers>
            <AppHeader />
            <main className="w-full relative flex-1 h-full">{children}</main>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
