import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import Providers from "@/common/context/providers";
import { AppSidebar } from "@/common/components/navigation/AppSidebar";
import "./globals.css";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Go&Gospel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <Providers>
          <AppSidebar />
          <main className="w-full relative">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
